# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  host: localhost
  database: real_skin_essentials_development
  user: <%= `whoami` %>
  password:

test:
  adapter: postgresql
  host: localhost
  database: real_skin_essentials_test
  user: <%= `whoami` %>
  password:

production:
  adapter: postgresql
  host: localhost
  database: real_skin_essentials_production
  user: <%= `whoami` %>
  password:
